SELECT FP.IDPRODUCTO, P.NOMBRE 
FROM FACTURA_PRODUCTO FP JOIN PRODUCTO P ON FP.IDPRODUCTO = P.IDPRODUCTO  
GROUP BY FP.IDPRODUCTO, P.NOMBRE, P.VALOR 
ORDER BY SUM(CANTIDAD)*P.VALOR DESC 
FETCH FIRST 1 ROWS ONLY;

SELECT 